from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()
from .models import db

class Company(db.Model):
    __tablename__ = 'company'
    id = db.Column(db.Integer, primary_key=True)
    symbol = db.Column(db.String(10), unique=True)
    cik = db.Column(db.String(20), unique=True)


class CompanyProfile(db.Model):
    __tablename__ = 'company_profile'
    id = db.Column(db.Integer, primary_key=True)
    company_id = db.Column(db.Integer, db.ForeignKey('company.id'))
    symbol = db.Column(db.String(10))
    price = db.Column(db.Float)
    beta = db.Column(db.Float)
    vol_avg = db.Column(db.BigInteger)
    mkt_cap = db.Column(db.BigInteger)
    last_div = db.Column(db.Float)
    range = db.Column(db.String(50))
    changes = db.Column(db.Float)
    company_name = db.Column(db.String(255))
    currency = db.Column(db.String(10))
    cik = db.Column(db.String(20))
    isin = db.Column(db.String(20))
    cusip = db.Column(db.String(20))
    exchange = db.Column(db.String(50))
    exchange_short_name = db.Column(db.String(20))
    industry = db.Column(db.String(255))
    website = db.Column(db.String(255))
    description = db.Column(db.Text)
    ceo = db.Column(db.String(255))
    sector = db.Column(db.String(255))
    country = db.Column(db.String(50))
    full_time_employees = db.Column(db.Integer)
    phone = db.Column(db.String(20))
    address = db.Column(db.String(255))
    city = db.Column(db.String(100))
    state = db.Column(db.String(50))
    zip = db.Column(db.String(20))
    dcf_diff = db.Column(db.Float)
    dcf = db.Column(db.Float)
    image = db.Column(db.String(255))
    ipo_date = db.Column(db.Date)
    default_image = db.Column(db.Boolean)
    is_etf = db.Column(db.Boolean)
    is_actively_trading = db.Column(db.Boolean)
    is_adr = db.Column(db.Boolean)
    is_fund = db.Column(db.Boolean)

class IncomeStatement(db.Model):
    __tablename__ = 'income_statement'
    id = db.Column(db.Integer, primary_key=True)
    company_id = db.Column(db.Integer, db.ForeignKey('company.id'))
    symbol = db.Column(db.String(10))
    date = db.Column(db.Date)
    cik = db.Column(db.String(20))
    filling_date = db.Column(db.Date)
    accepted_date = db.Column(db.TIMESTAMP)
    calendar_year = db.Column(db.Integer)
    period = db.Column(db.String(5))
    revenue = db.Column(db.Float)
    cost_of_revenue = db.Column(db.Float)
    gross_profit = db.Column(db.Float)
    gross_profit_ratio = db.Column(db.Float)
    research_and_development_expenses = db.Column(db.Float)
    general_and_administrative_expenses = db.Column(db.Float)
    selling_and_marketing_expenses = db.Column(db.Float)
    selling_general_and_administrative_expenses = db.Column(db.Float)
    other_expenses = db.Column(db.Float)
    operating_expenses = db.Column(db.Float)
    cost_and_expenses = db.Column(db.Float)
    interest_income = db.Column(db.Float)
    interest_expense = db.Column(db.Float)
    depreciation_and_amortization = db.Column(db.Float)
    ebitda = db.Column(db.Float)
    ebitda_ratio = db.Column(db.Float)
    operating_income = db.Column(db.Float)
    operating_income_ratio = db.Column(db.Float)
    total_other_income_expenses_net = db.Column(db.Float)
    income_before_tax = db.Column(db.Float)
    income_before_tax_ratio = db.Column(db.Float)
    income_tax_expense = db.Column(db.Float)
    net_income = db.Column(db.Float)
    net_income_ratio = db.Column(db.Float)
    eps = db.Column(db.Float)
    eps_diluted = db.Column(db.Float)
    weighted_average_shs_out = db.Column(db.Float)
    weighted_average_shs_out_dil = db.Column(db.Float)
    link = db.Column(db.String)
    final_link = db.Column(db.String)

class BalanceSheet(db.Model):
    __tablename__ = 'balance_sheet'
    id = db.Column(db.Integer, primary_key=True)
    company_id = db.Column(db.Integer, db.ForeignKey('company.id'))
    symbol = db.Column(db.String(10))
    date = db.Column(db.Date)
    reported_currency = db.Column(db.String(10))
    cik = db.Column(db.String(20))
    filling_date = db.Column(db.Date)
    accepted_date = db.Column(db.TIMESTAMP)
    calendar_year = db.Column(db.Integer)
    period = db.Column(db.String(5))
    cash_and_cash_equivalents = db.Column(db.Float)
    short_term_investments = db.Column(db.Float)
    cash_and_short_term_investments = db.Column(db.Float)
    net_receivables = db.Column(db.Float)
    inventory = db.Column(db.Float)
    other_current_assets = db.Column(db.Float)
    total_current_assets = db.Column(db.Float)
    property_plant_equipment_net = db.Column(db.Float)
    goodwill = db.Column(db.Float)
    intangible_assets = db.Column(db.Float)
    goodwill_and_intangible_assets = db.Column(db.Float)
    long_term_investments = db.Column(db.Float)
    tax_assets = db.Column(db.Float)
    other_non_current_assets = db.Column(db.Float)
    total_non_current_assets = db.Column(db.Float)
    other_assets = db.Column(db.Float)
    total_assets = db.Column(db.Float)
    account_payables = db.Column(db.Float)
    short_term_debt = db.Column(db.Float)
    tax_payables = db.Column(db.Float)
    deferred_revenue = db.Column(db.Float)
    other_current_liabilities = db.Column(db.Float)
    total_current_liabilities = db.Column(db.Float)
    long_term_debt = db.Column(db.Float)
    deferred_revenue_non_current = db.Column(db.Float)
    deferred_tax_liabilities_non_current = db.Column(db.Float)
    other_non_current_liabilities = db.Column(db.Float)
    total_non_current_liabilities = db.Column(db.Float)
    other_liabilities = db.Column(db.Float)
    capital_lease_obligations = db.Column(db.Float)
    total_liabilities = db.Column(db.Float)
    preferred_stock = db.Column(db.Float)
    common_stock = db.Column(db.Float)
    retained_earnings = db.Column(db.Float)
    accumulated_other_comprehensive_income_loss = db.Column(db.Float)
    othertotal_stockholders_equity = db.Column(db.Float)
    total_stockholders_equity = db.Column(db.Float)
    total_equity = db.Column(db.Float)
    total_liabilities_and_stockholders_equity = db.Column(db.Float)
    minority_interest = db.Column(db.Float)
    total_liabilities_and_total_equity = db.Column(db.Float)
    total_investments = db.Column(db.Float)
    total_debt = db.Column(db.Float)
    net_debt = db.Column(db.Float)
    link = db.Column(db.String)
    final_link = db.Column(db.String)

class CashFlowStatement(db.Model):
    __tablename__ = 'cash_flow_statement'
    id = db.Column(db.Integer, primary_key=True)
    company_id = db.Column(db.Integer, db.ForeignKey('company.id'))
    symbol = db.Column(db.String(10))
    date = db.Column(db.Date)
    reported_currency = db.Column(db.String(10))
    cik = db.Column(db.String(20))
    filling_date = db.Column(db.Date)
    accepted_date = db.Column(db.TIMESTAMP)
    calendar_year = db.Column(db.Integer)
    period = db.Column(db.String(5))
    net_income = db.Column(db.Float)
    depreciation_and_amortization = db.Column(db.Float)
    deferred_income_tax = db.Column(db.Float)
    stock_based_compensation = db.Column(db.Float)
    change_in_working_capital = db.Column(db.Float)
    accounts_receivables = db.Column(db.Float)
    inventory = db.Column(db.Float)
    accounts_payables = db.Column(db.Float)
    other_working_capital = db.Column(db.Float)
    other_non_cash_items = db.Column(db.Float)
    net_cash_provided_by_operating_activities = db.Column(db.Float)
    investments_in_property_plant_and_equipment = db.Column(db.Float)
    acquisitions_net = db.Column(db.Float)
    purchases_of_investments = db.Column(db.Float)
    sales_maturities_of_investments = db.Column(db.Float)
    other_investing_activites = db.Column(db.Float)
    net_cash_used_for_investing_activites = db.Column(db.Float)
    debt_repayment = db.Column(db.Float)
    common_stock_issued = db.Column(db.Float)
    common_stock_repurchased = db.Column(db.Float)
    dividends_paid = db.Column(db.Float)
    other_financing_activites = db.Column(db.Float)
    net_cash_used_provided_by_financing_activities = db.Column(db.Float)
    effect_of_forex_changes_on_cash = db.Column(db.Float)
    net_change_in_cash = db.Column(db.Float)
    cash_at_end_of_period = db.Column(db.Float)
    cash_at_beginning_of_period = db.Column(db.Float)
    operating_cash_flow = db.Column(db.Float)
    capital_expenditure = db.Column(db.Float)
    free_cash_flow = db.Column(db.Float)
    link = db.Column(db.String)
    final_link = db.Column(db.String)

class FinancialRatios(db.Model):
    __tablename__ = 'financial_ratios'
    id = db.Column(db.Integer, primary_key=True)
    company_id = db.Column(db.Integer, db.ForeignKey('company.id'))
    date = db.Column(db.Date)
    gross_margin = db.Column(db.Float)
    operating_margin = db.Column(db.Float)
    net_margin = db.Column(db.Float)
    return_on_assets = db.Column(db.Float)
    return_on_equity = db.Column(db.Float)
    return_on_invested_capital = db.Column(db.Float)
    current_ratio = db.Column(db.Float)
    quick_ratio = db.Column(db.Float)
    cash_ratio = db.Column(db.Float)
    debt_to_equity = db.Column(db.Float)
    debt_to_assets = db.Column(db.Float)
    interest_coverage = db.Column(db.Float)
    asset_turnover = db.Column(db.Float)
    inventory_turnover = db.Column(db.Float)
    days_sales_in_inventory = db.Column(db.Float)
    days_sales_outstanding = db.Column(db.Float)
    days_payable_outstanding = db.Column(db.Float)
    revenue_growth = db.Column(db.Float)
    net_income_growth = db.Column(db.Float)
    total_assets_growth = db.Column(db.Float)
    total_equity_growth = db.Column(db.Float)
    total_liabilities_growth = db.Column(db.Float)
    dividend_payout_ratio = db.Column(db.Float)
    dividend_yield = db.Column(db.Float)
    price_to_earnings = db.Column(db.Float)
    price_to_sales = db.Column(db.Float)
    price_to_book = db.Column(db.Float)
    enterprise_value = db.Column(db.Float)
    enterprise_value_to_revenue = db.Column(db.Float)
    enterprise_value_to_ebitda = db.Column(db.Float)
